[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  call deoplete#custom#option({
    \   'ignore_case': v:true,
    \   'smart_case': v:true,
    \ })
'''

[[plugins]]
repo = 'Shougo/deoplete-rct'

# deoplete on vim requires plugin 1/2
[[plugins]]
repo = 'roxma/nvim-yarp'

# deoplete on vim requires plugin 2/2
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'Shougo/denite.nvim'

